import type { GameDefinition } from './types'

export const gameCatalog: GameDefinition[] = [
  {
    id: 'aurora-sync',
    title: 'Aurora Sync',
    summary: 'Tap drifting lights in order to lock tonight\'s shared orbit.',
    icon: '🌌',
    category: 'ritual',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'lavender',
    resolver: 'starlight-connect',
    tags: ['taps', 'soothing'],
  },
  {
    id: 'memory-koi',
    title: 'Memory Koi Pond',
    summary: 'Trace three floating koi before they fade under the surface.',
    icon: '🐟',
    category: 'memory',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'mint',
    resolver: 'starlight-connect',
    tags: ['pattern', 'calm'],
  },
  {
    id: 'starlight-relay',
    title: 'Starlight Relay',
    summary: 'Activate each quadrant of the night sky to pass the beacon forward.',
    icon: '✨',
    category: 'speed',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'blush',
    resolver: 'emoji-forage',
    tags: ['reflex', 'tiny'],
  },
  {
    id: 'petal-compass',
    title: 'Petal Compass',
    summary: 'Align petals as they spin to point toward home.',
    icon: '🌸',
    category: 'puzzle',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'lavender',
    resolver: 'harmony-sum',
    tags: ['logic', 'calm'],
  },
  {
    id: 'tender-orbit',
    title: 'Tender Orbit',
    summary: 'Compose a quick compliment to keep our atmosphere steady.',
    icon: '🪐',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'mint',
    resolver: 'compliment-crafter',
    tags: ['writing', 'prompt'],
  },
  {
    id: 'cozy-signal',
    title: 'Cozy Signal',
    summary: 'Pick the right words to broadcast tonight\'s love note.',
    icon: '📡',
    category: 'story',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'blush',
    resolver: 'story-spark',
    tags: ['writing', 'soft'],
  },
  {
    id: 'moonbeam-mix',
    title: 'Moonbeam Mix',
    summary: 'Catch three matching emoji beams before they disappear.',
    icon: '🌙',
    category: 'speed',
    difficulty: 'Spicy',
    duration: '1 min',
    accent: 'ink',
    resolver: 'emoji-forage',
    tags: ['tap', 'speed'],
  },
  {
    id: 'cloud-tether',
    title: 'Cloud Tether',
    summary: 'Balance drifting clouds so the skyline stays still.',
    icon: '☁️',
    category: 'calm',
    difficulty: 'Cozy',
    duration: '4 min',
    accent: 'lavender',
    resolver: 'harmony-sum',
    tags: ['balance', 'slow'],
  },
  {
    id: 'sprout-sketch',
    title: 'Sprout Sketch',
    summary: 'Describe where the next shared houseplant will live.',
    icon: '🌱',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'mint',
    resolver: 'story-spark',
    tags: ['writing', 'garden'],
  },
  {
    id: 'warmth-relay',
    title: 'Warmth Relay',
    summary: 'Send three emoji hugs through the tunnel without repeats.',
    icon: '🤗',
    category: 'micro',
    difficulty: 'Chill',
    duration: '1 min',
    accent: 'blush',
    resolver: 'emoji-forage',
    tags: ['tap', 'loop'],
  },
  {
    id: 'secret-courier',
    title: 'Secret Courier',
    summary: 'Draft a one-sentence mission for tomorrow\'s surprise.',
    icon: '📨',
    category: 'story',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'lavender',
    resolver: 'story-spark',
    tags: ['mission', 'prompt'],
  },
  {
    id: 'pixel-picnic',
    title: 'Pixel Picnic',
    summary: 'Pick flavors for an imaginary picnic spread.',
    icon: '🧺',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'mint',
    resolver: 'compliment-crafter',
    tags: ['choices', 'silly'],
  },
  {
    id: 'lavender-sprint',
    title: 'Lavender Sprint',
    summary: 'Race to tap the lavender icons before they fade.',
    icon: '💜',
    category: 'speed',
    difficulty: 'Spicy',
    duration: '1 min',
    accent: 'lavender',
    resolver: 'emoji-forage',
    tags: ['speed', 'reflex'],
  },
  {
    id: 'wishful-loom',
    title: 'Wishful Loom',
    summary: 'Choose threads to weave tonight\'s mantra.',
    icon: '🧶',
    category: 'ritual',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'blush',
    resolver: 'compliment-crafter',
    tags: ['affirmation', 'calm'],
  },
  {
    id: 'firefly-drift',
    title: 'Firefly Drift',
    summary: 'Illuminate hidden fireflies with accurate taps.',
    icon: '🪲',
    category: 'speed',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'emoji-forage',
    tags: ['tap', 'light'],
  },
  {
    id: 'lighthouse-call',
    title: 'Lighthouse Call',
    summary: 'Sequence beams in the correct order to guide the ferry.',
    icon: '🚨',
    category: 'logic',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'ink',
    resolver: 'harmony-sum',
    tags: ['sequence', 'calm'],
  },
  {
    id: 'midnight-pantry',
    title: 'Midnight Pantry',
    summary: 'Draft a menu for an after-dark snack raid.',
    icon: '🍪',
    category: 'story',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'lavender',
    resolver: 'story-spark',
    tags: ['food', 'prompt'],
  },
  {
    id: 'heartline-dash',
    title: 'Heartline Dash',
    summary: 'Keep the pulse balanced by solving quick sums.',
    icon: '💓',
    category: 'logic',
    difficulty: 'Spicy',
    duration: '2 min',
    accent: 'blush',
    resolver: 'harmony-sum',
    tags: ['math', 'speed'],
  },
  {
    id: 'velvet-path',
    title: 'Velvet Path',
    summary: 'Describe the coziest path you\'d walk tonight.',
    icon: '🛤️',
    category: 'story',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'mint',
    resolver: 'story-spark',
    tags: ['writing', 'walk'],
  },
  {
    id: 'soft-armor',
    title: 'Soft Armor',
    summary: 'Select three compliment charms to equip.',
    icon: '🛡️',
    category: 'creative',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'lavender',
    resolver: 'compliment-crafter',
    tags: ['affirmation', 'gear'],
  },
  {
    id: 'lyric-loop',
    title: 'Lyric Loop',
    summary: 'Fill in the blanks of our imaginary chorus.',
    icon: '🎧',
    category: 'story',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'blush',
    resolver: 'story-spark',
    tags: ['music', 'prompt'],
  },
  {
    id: 'coop-pulse',
    title: 'Co-op Pulse',
    summary: 'Match energy tiles to keep the pulse centered.',
    icon: '🫶',
    category: 'logic',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'harmony-sum',
    tags: ['balance', 'logic'],
  },
  {
    id: 'hometown-echo',
    title: 'Hometown Echo',
    summary: 'Write a memory postcard from a shared landmark.',
    icon: '🏙️',
    category: 'story',
    difficulty: 'Cozy',
    duration: '4 min',
    accent: 'lavender',
    resolver: 'story-spark',
    tags: ['memory', 'writing'],
  },
  {
    id: 'petal-riddle',
    title: 'Petal Riddle',
    summary: 'Tap the correct blossoms before the wind steals them.',
    icon: '💮',
    category: 'speed',
    difficulty: 'Spicy',
    duration: '1 min',
    accent: 'blush',
    resolver: 'emoji-forage',
    tags: ['tap', 'floral'],
  },
  {
    id: 'aurora-traces',
    title: 'Aurora Traces',
    summary: 'Anchor each aurora beam without breaking the glow.',
    icon: '🌈',
    category: 'ritual',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'mint',
    resolver: 'starlight-connect',
    tags: ['pattern', 'calm'],
  },
  {
    id: 'lucky-loom',
    title: 'Lucky Loom',
    summary: 'Craft a gratitude weave with three bright threads.',
    icon: '🪢',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'blush',
    resolver: 'compliment-crafter',
    tags: ['gratitude', 'prompt'],
  },
  {
    id: 'sugar-nebula',
    title: 'Sugar Nebula',
    summary: 'Collect matching sweets swirling in orbit.',
    icon: '🍬',
    category: 'micro',
    difficulty: 'Chill',
    duration: '1 min',
    accent: 'lavender',
    resolver: 'emoji-forage',
    tags: ['tap', 'sugar'],
  },
  {
    id: 'mint-embers',
    title: 'Mint Embers',
    summary: 'Balance ember values to brew the perfect tea.',
    icon: '🍵',
    category: 'puzzle',
    difficulty: 'Cozy',
    duration: '4 min',
    accent: 'mint',
    resolver: 'harmony-sum',
    tags: ['math', 'tea'],
  },
  {
    id: 'honey-circuit',
    title: 'Honey Circuit',
    summary: 'Choose three adjectives that taste like honey.',
    icon: '🍯',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'blush',
    resolver: 'compliment-crafter',
    tags: ['sweet', 'writing'],
  },
  {
    id: 'star-carta',
    title: 'Star Carta',
    summary: 'Describe the first stop on our cosmic road trip.',
    icon: '🗺️',
    category: 'story',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'lavender',
    resolver: 'story-spark',
    tags: ['travel', 'writing'],
  },
  {
    id: 'lantern-steps',
    title: 'Lantern Steps',
    summary: 'Activate glowing tiles in order from dim to bright.',
    icon: '🏮',
    category: 'logic',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'starlight-connect',
    tags: ['pattern', 'focus'],
  },
  {
    id: 'wish-courier',
    title: 'Wish Courier',
    summary: 'Write a single sentence wish for a stranger.',
    icon: '💫',
    category: 'story',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'blush',
    resolver: 'story-spark',
    tags: ['kindness', 'prompt'],
  },
  {
    id: 'garden-signal',
    title: 'Garden Signal',
    summary: 'Sequence sprouts to guide pollinators home.',
    icon: '🪴',
    category: 'memory',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'starlight-connect',
    tags: ['sequence', 'nature'],
  },
  {
    id: 'dream-dial',
    title: 'Dream Dial',
    summary: 'Select adjectives to tune tonight\'s dream mood.',
    icon: '🌀',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'lavender',
    resolver: 'compliment-crafter',
    tags: ['mood', 'prompt'],
  },
  {
    id: 'solstice-stack',
    title: 'Solstice Stack',
    summary: 'Stack energy tokens to match the day length.',
    icon: '☀️',
    category: 'logic',
    difficulty: 'Chill',
    duration: '4 min',
    accent: 'ink',
    resolver: 'harmony-sum',
    tags: ['math', 'seasonal'],
  },
  {
    id: 'pastel-relay',
    title: 'Pastel Relay',
    summary: 'Tag pastel emoji before the timer chirps.',
    icon: '🎨',
    category: 'speed',
    difficulty: 'Spicy',
    duration: '1 min',
    accent: 'lavender',
    resolver: 'emoji-forage',
    tags: ['tap', 'color'],
  },
  {
    id: 'soft-groove',
    title: 'Soft Groove',
    summary: 'Write the opening line of a slow dance playlist.',
    icon: '💃',
    category: 'story',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'blush',
    resolver: 'story-spark',
    tags: ['music', 'writing'],
  },
  {
    id: 'pocket-chorus',
    title: 'Pocket Chorus',
    summary: 'Pick three words that sound like a chorus hook.',
    icon: '🎤',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'mint',
    resolver: 'compliment-crafter',
    tags: ['music', 'prompt'],
  },
  {
    id: 'petal-print',
    title: 'Petal Print',
    summary: 'Trace petals in the right order to stamp the message.',
    icon: '🖋️',
    category: 'memory',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'lavender',
    resolver: 'starlight-connect',
    tags: ['sequence', 'calm'],
  },
  {
    id: 'glint-gram',
    title: 'Glint Gram',
    summary: 'Catch the right sparkle emoji chain.',
    icon: '📸',
    category: 'micro',
    difficulty: 'Spicy',
    duration: '1 min',
    accent: 'blush',
    resolver: 'emoji-forage',
    tags: ['tap', 'glitter'],
  },
  {
    id: 'peppermint-plot',
    title: 'Peppermint Plot',
    summary: 'Balance mint leaves to finish the coaster pattern.',
    icon: '🍃',
    category: 'puzzle',
    difficulty: 'Chill',
    duration: '4 min',
    accent: 'mint',
    resolver: 'harmony-sum',
    tags: ['logic', 'pattern'],
  },
  {
    id: 'ribbon-serpent',
    title: 'Ribbon Serpent',
    summary: 'Choose adjectives to describe a mythical ribbon creature.',
    icon: '🐉',
    category: 'story',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'ink',
    resolver: 'story-spark',
    tags: ['fantasy', 'writing'],
  },
  {
    id: 'morning-orbit',
    title: 'Morning Orbit',
    summary: 'Select the morning rituals that keep us synced.',
    icon: '⏰',
    category: 'ritual',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'mint',
    resolver: 'compliment-crafter',
    tags: ['routine', 'prompt'],
  },
  {
    id: 'skyline-stitch',
    title: 'Skyline Stitch',
    summary: 'Connect skyline lights without crossing threads.',
    icon: '🌃',
    category: 'puzzle',
    difficulty: 'Chill',
    duration: '4 min',
    accent: 'lavender',
    resolver: 'starlight-connect',
    tags: ['pattern', 'city'],
  },
  {
    id: 'meadow-cipher',
    title: 'Meadow Cipher',
    summary: 'Balance meadow clues to unlock the code.',
    icon: '🌾',
    category: 'logic',
    difficulty: 'Spicy',
    duration: '3 min',
    accent: 'mint',
    resolver: 'harmony-sum',
    tags: ['math', 'nature'],
  },
  {
    id: 'velvet-wake',
    title: 'Velvet Wake',
    summary: 'Describe the dream you\'d like to wake from.',
    icon: '🛌',
    category: 'story',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'blush',
    resolver: 'story-spark',
    tags: ['dream', 'writing'],
  },
  {
    id: 'secret-riser',
    title: 'Secret Riser',
    summary: 'Pick code words to schedule a surprise breakfast.',
    icon: '🥞',
    category: 'creative',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'compliment-crafter',
    tags: ['breakfast', 'prompt'],
  },
  {
    id: 'pillow-sprint',
    title: 'Pillow Sprint',
    summary: 'Tap the sleepy emoji before they nap.',
    icon: '💤',
    category: 'speed',
    difficulty: 'Spicy',
    duration: '1 min',
    accent: 'lavender',
    resolver: 'emoji-forage',
    tags: ['tap', 'sleep'],
  },
  {
    id: 'sugarplane',
    title: 'Sugarplane',
    summary: 'Balance sweetness in a dessert flight.',
    icon: '🍰',
    category: 'puzzle',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'blush',
    resolver: 'harmony-sum',
    tags: ['math', 'dessert'],
  },
  {
    id: 'comet-pledge',
    title: 'Comet Pledge',
    summary: 'Write a promise you\'d send by comet tail.',
    icon: '☄️',
    category: 'story',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'ink',
    resolver: 'story-spark',
    tags: ['promise', 'writing'],
  },
  {
    id: 'warm-signal',
    title: 'Warm Signal',
    summary: 'Choose signals that mean “I\'m thinking of you”.',
    icon: '📶',
    category: 'ritual',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'mint',
    resolver: 'compliment-crafter',
    tags: ['signals', 'prompt'],
  },
  {
    id: 'gemstone-stack',
    title: 'Gemstone Stack',
    summary: 'Stack glowing stones to unlock the cove.',
    icon: '💎',
    category: 'puzzle',
    difficulty: 'Chill',
    duration: '4 min',
    accent: 'lavender',
    resolver: 'harmony-sum',
    tags: ['math', 'shine'],
  },
  {
    id: 'blossom-rally',
    title: 'Blossom Rally',
    summary: 'Catch blossoms that match the queued emoji.',
    icon: '🌷',
    category: 'speed',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'emoji-forage',
    tags: ['tap', 'floral'],
  },
  {
    id: 'lunar-prompts',
    title: 'Lunar Prompts',
    summary: 'Write a night note using moonlit words.',
    icon: '🌔',
    category: 'story',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'lavender',
    resolver: 'story-spark',
    tags: ['moon', 'writing'],
  },
  {
    id: 'cozy-equinox',
    title: 'Cozy Equinox',
    summary: 'Balance day and night tiles equally.',
    icon: '⚖️',
    category: 'logic',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'blush',
    resolver: 'harmony-sum',
    tags: ['balance', 'math'],
  },
  {
    id: 'fable-jog',
    title: 'Fable Jog',
    summary: 'Describe a tiny adventure that lasts ten minutes.',
    icon: '🏃‍♀️',
    category: 'story',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'mint',
    resolver: 'story-spark',
    tags: ['adventure', 'writing'],
  },
  {
    id: 'harbor-wish',
    title: 'Harbor Wish',
    summary: 'Compose a harbor wish using saltwater words.',
    icon: '⚓',
    category: 'creative',
    difficulty: 'Chill',
    duration: '3 min',
    accent: 'lavender',
    resolver: 'compliment-crafter',
    tags: ['water', 'prompt'],
  },
  {
    id: 'dusk-zine',
    title: 'Dusk Zine',
    summary: 'Pick page themes for a micro zine about us.',
    icon: '📒',
    category: 'creative',
    difficulty: 'Cozy',
    duration: '3 min',
    accent: 'blush',
    resolver: 'compliment-crafter',
    tags: ['zine', 'prompt'],
  },
  {
    id: 'everglow-thread',
    title: 'Everglow Thread',
    summary: 'Trace shimmering threads before they fade.',
    icon: '🧵',
    category: 'memory',
    difficulty: 'Chill',
    duration: '2 min',
    accent: 'mint',
    resolver: 'starlight-connect',
    tags: ['pattern', 'glow'],
  },
  {
    id: 'crescent-mixer',
    title: 'Crescent Mixer',
    summary: 'Mix moon phrases into a fresh bedtime toast.',
    icon: '🥂',
    category: 'story',
    difficulty: 'Cozy',
    duration: '2 min',
    accent: 'lavender',
    resolver: 'story-spark',
    tags: ['toast', 'writing'],
  },
]
